language: java
services:
  - docker
  - postgresql
before_install:
  - sudo service postgresql stop
#  - docker run --name goal_todo_list -e POSTGRES_PASSWORD=password -e POSTGRES_DB=goal_todo_list -d -p 5432:5432 postgres
