spring:
  datasource:
    url: jdbc:mysql://localhost:3306/goal_todo_list?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create