spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/goal_todo_list?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false
    username: postgres
    password: password
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: validate
    database: postgresql
    properties.hibernate.enable_lazy_load_no_trans: true
  liquibase:
    change-log: "classpath:config/liquibase/master.xml"
